# Generated by Django 3.0.6 on 2020-05-12 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploader_name', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('album', 'created_on')},
        ),
    ]
