# Generated by Django 3.0.6 on 2020-05-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200512_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='id',
            new_name='song_id',
        ),
    ]
