# Generated by Django 3.0.6 on 2020-05-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20200512_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='user',
            new_name='owner',
        ),
    ]
