# Generated by Django 2.2.6 on 2019-11-24 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ['created_at']},
        ),
    ]
