# Generated by Django 2.2.6 on 2019-10-31 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('album_thumbnail', models.ImageField(upload_to='album')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('genre_thumbnail', models.ImageField(upload_to='genre')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('audio_id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Title', max_length=200, verbose_name='Song name')),
                ('description', models.CharField(default='', max_length=200)),
                ('song_thumbnail', models.ImageField(blank=True, default='https://django-music-test-bucket.s3-us-west-2.amazonaws.com/photos/flutter_logo.png', upload_to='thumbnail')),
                ('song_url', models.FileField(upload_to='music')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.Artist')),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.Genre')),
            ],
        ),
    ]
