# Generated by Django 2.2.6 on 2019-10-22 10:57

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
    ]
