# Generated by Django 2.2.6 on 2019-10-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191022_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='description',
            field=models.TextField(default='This is the description'),
        ),
        migrations.AddField(
            model_name='song',
            name='thumbnail',
            field=models.ImageField(default='https://django-music-test-bucket.s3-us-west-2.amazonaws.com/photos/flutter_logo.png', upload_to='thumbnail'),
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='Title', max_length=200, verbose_name='Song name'),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='music'),
        ),
    ]
