# Generated by Django 2.2.6 on 2019-10-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='albumName',
        ),
        migrations.RenameField(
            model_name='genre',
            old_name='name',
            new_name='genreName',
        ),
        migrations.AlterField(
            model_name='song',
            name='song_thumbnail',
            field=models.ImageField(upload_to='songsImages'),
        ),
    ]
