# Generated by Django 2.2.6 on 2019-11-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20191031_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.Album'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to='artist.Artist'),
        ),
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='music.Genre'),
        ),
    ]
