# Generated by Django 2.2.6 on 2019-11-24 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20191124_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('album', 'created_on')},
        ),
    ]
